defmodule SertantaiControls.Repo.Migrations.AddUserRoleAndConfirmedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :name
      modify :organization_id, :uuid, null: true
      add :role, :text
      add :confirmed_at, :utc_datetime_usec
    end

    drop constraint(:quadrant_classifications, "quadrant_classifications_control_id_fkey")

    alter table(:quadrant_classifications) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "quadrant_classifications_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:organizational_traces, "organizational_traces_control_id_fkey")

    alter table(:organizational_traces) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "organizational_traces_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:control_interactions, "control_interactions_control_id_fkey")

    alter table(:control_interactions) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "control_interactions_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:competency_records, "competency_records_control_id_fkey")

    alter table(:competency_records) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "competency_records_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:competency_records, "competency_records_control_id_fkey")

    alter table(:competency_records) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "competency_records_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:control_interactions, "control_interactions_control_id_fkey")

    alter table(:control_interactions) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "control_interactions_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:organizational_traces, "organizational_traces_control_id_fkey")

    alter table(:organizational_traces) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "organizational_traces_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:quadrant_classifications, "quadrant_classifications_control_id_fkey")

    alter table(:quadrant_classifications) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "quadrant_classifications_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      remove :confirmed_at
      remove :role
      modify :organization_id, :uuid, null: false
      add :name, :text
    end
  end
end
