defmodule SertantaiControls.Repo.Migrations.CreateRiskControlSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :name, :text
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:quadrant_classifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :control_id, :uuid, null: false
      add :quadrant, :text, null: false
      add :time_since_touched_days, :bigint
      add :provider_distance, :decimal
      add :classified_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      add :reason, :text
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:provider_networks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_provider_id, :uuid, null: false
      add :to_provider_id, :uuid, null: false
      add :relationship_type, :text
      add :path_weight, :decimal, default: "1.0"
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:organizational_traces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :control_id, :uuid, null: false
      add :trace_type, :text, null: false
      add :description, :text
      add :recorded_by_user_id, :uuid
      add :recorded_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      add :related_incident_id, :uuid
      add :severity, :text
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:controls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:quadrant_classifications) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "quadrant_classifications_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizational_traces) do
      modify :control_id,
             references(:controls,
               column: :id,
               name: "organizational_traces_control_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :recorded_by_user_id,
             references(:users,
               column: :id,
               name: "organizational_traces_recorded_by_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:controls) do
      add :name, :text, null: false
      add :description, :text
      add :control_type, :text
      add :last_touched_at, :utc_datetime_usec
      add :last_touched_by_user_id, :uuid
      add :provider_distance, :decimal, default: "0"
      add :current_quadrant, :text, default: "self"
      add :functional_range, :text, default: "wide"
      add :failure_probability, :decimal
      add :requires_refresher_training, :boolean, default: false
      add :primary_provider_id, :uuid, null: false
      add :owned_by_user, :boolean, default: false
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:control_providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:provider_networks) do
      modify :from_provider_id,
             references(:control_providers,
               column: :id,
               name: "provider_networks_from_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :to_provider_id,
             references(:control_providers,
               column: :id,
               name: "provider_networks_to_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:controls) do
      modify :primary_provider_id,
             references(:control_providers,
               column: :id,
               name: "controls_primary_provider_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "controls_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:control_providers) do
      add :name, :text, null: false
      add :provider_type, :text, null: false
      add :contact_info, :map
      add :is_user_themselves, :boolean, default: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "control_providers_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:control_interactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :control_id,
          references(:controls,
            column: :id,
            name: "control_interactions_control_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "control_interactions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :interaction_type, :text, null: false
      add :duration_minutes, :bigint
      add :notes, :text
      add :issues_found, :boolean, default: false
      add :quadrant_before, :text
      add :quadrant_after, :text
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:competency_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "competency_records_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :control_id,
          references(:controls,
            column: :id,
            name: "competency_records_control_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :competency_level, :text, default: "novice"
      add :last_training_date, :date
      add :next_refresher_due, :date
      add :training_hours, :decimal, default: "0"
      add :certified_by, :text
      add :certification_expires, :date
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:competency_records, "competency_records_user_id_fkey")

    drop constraint(:competency_records, "competency_records_control_id_fkey")

    drop table(:competency_records)

    drop constraint(:control_interactions, "control_interactions_control_id_fkey")

    drop constraint(:control_interactions, "control_interactions_user_id_fkey")

    drop table(:control_interactions)

    drop constraint(:control_providers, "control_providers_organization_id_fkey")

    alter table(:control_providers) do
      remove :updated_at
      remove :inserted_at
      remove :organization_id
      remove :is_user_themselves
      remove :contact_info
      remove :provider_type
      remove :name
    end

    drop constraint(:controls, "controls_primary_provider_id_fkey")

    drop constraint(:controls, "controls_organization_id_fkey")

    alter table(:controls) do
      modify :organization_id, :uuid
      modify :primary_provider_id, :uuid
    end

    drop constraint(:provider_networks, "provider_networks_from_provider_id_fkey")

    drop constraint(:provider_networks, "provider_networks_to_provider_id_fkey")

    alter table(:provider_networks) do
      modify :to_provider_id, :uuid
      modify :from_provider_id, :uuid
    end

    drop table(:control_providers)

    alter table(:controls) do
      remove :updated_at
      remove :inserted_at
      remove :organization_id
      remove :owned_by_user
      remove :primary_provider_id
      remove :requires_refresher_training
      remove :failure_probability
      remove :functional_range
      remove :current_quadrant
      remove :provider_distance
      remove :last_touched_by_user_id
      remove :last_touched_at
      remove :control_type
      remove :description
      remove :name
    end

    drop constraint(:organizational_traces, "organizational_traces_control_id_fkey")

    drop constraint(:organizational_traces, "organizational_traces_recorded_by_user_id_fkey")

    alter table(:organizational_traces) do
      modify :recorded_by_user_id, :uuid
      modify :control_id, :uuid
    end

    drop constraint(:quadrant_classifications, "quadrant_classifications_control_id_fkey")

    alter table(:quadrant_classifications) do
      modify :control_id, :uuid
    end

    drop table(:controls)

    drop table(:organizational_traces)

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:users, "users_organization_id_fkey")

    alter table(:users) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop table(:provider_networks)

    drop table(:quadrant_classifications)

    drop table(:users)
  end
end
